### ISSUE TITLE
Exercise 2.29 有疑问

### ISSUE THREAD

**Issue by husnda** [huangmingchuan/Cpp_Primer_Answers#13]
练习 2.29
(b)为什么const指针不能赋值给普通指针？_http://www.cnblogs.com/mylinux/archive/2013/04/27/3047719.html_
网页上有“_**常指针可以赋值给一个普通指针**_”；
(d)(e)(f)为什么是正确的？
_https://github.com/Mooophy/Cpp-Primer/tree/master/ch02_
与英文版冲突？
求解。

**Comment by husnda** [comment]
事实上const指针可以赋值给普通指针，"_const int *const p3;_"既将p3定义为const pointer又定义为pointer to const，而造成_p1=p3_非法的原因是**_指向常量的指针(pointer to const)不可以赋值给普通指针_**，另外(d)(e)(f)确实是非法的，详见英文版解释。
**这个答案有错误，希望作者能修正。**
且我感觉这个repository已经没有人维护了，相关issues也无从解决，希望看到这个issue的初学者早日转投英文版怀抱，避免被误导。

**Comment by Focus5679** [comment]
> 
> 
> 事实上const指针可以赋值给普通指针，"_const int *const p3;_"既将p3定义为const pointer又定义为pointer to const，而造成_p1=p3_非法的原因是**指向常量的指针(pointer to const)不可以赋值给普通指针**，另外(d)(e)(f)确实是非法的，详见英文版解释。
> **这个答案有错误，希望作者能修正。**
> 且我感觉这个repository已经没有人维护了，相关issues也无从解决，希望看到这个issue的初学者早日转投英文版怀抱，避免被误导。

我在学习过程中同样发现了这个问题，十分感谢前辈提醒，希望请教下前辈哪里还有比较好的中文练习解答？英文看起来还是有点吃力。

**Comment by jokerkeny** [comment]
同发现ef的问题
b是非法的，只不过原因不是作者说的p3是个const指针，应该是，“p3是指向const的指针”

**Comment by jokerkeny** [comment]
> 事实上const指针可以赋值给普通指针，"_const int *const p3;_"既将p3定义为const pointer又定义为pointer to const，而造成_p1=p3_非法的原因是**指向常量的指针(pointer to const)不可以赋值给普通指针**，另外(d)(e)(f)确实是非法的，详见英文版解释。
> **这个答案有错误，希望作者能修正。**
> 且我感觉这个repository已经没有人维护了，相关issues也无从解决，希望看到这个issue的初学者早日转投英文版怀抱，避免被误导。

可以中文版书+英文版答案啊哈哈

**Comment by noyidoit** [comment]
> > 事实上const指针可以赋值给普通指针，"_const int *const p3;_"既将p3定义为const pointer又定义为pointer to const，而造成_p1=p3_非法的原因是**指向常量的指针(pointer to const)不可以赋值给普通指针**，另外(d)(e)(f)确实是非法的，详见英文版解释。
> > **这个答案有错误，希望作者能修正。**
> > 且我感觉这个repository已经没有人维护了，相关issues也无从解决，希望看到这个issue的初学者早日转投英文版怀抱，避免被误导。
> 
> 可以中文版书+英文版答案啊哈哈

中文版和英文版有些题目不完全一样......
比如ex3.17 格式要求不一样.
不过大体上应该是没问题的.
