### ISSUE TITLE
exercise 2.32

### ISSUE THREAD

**Issue by aimergenge** [huangmingchuan/Cpp_Primer_Answers#14]
If you write code like `int null = 0, *p = null`, you will get a error:
you can not init a int* with a int

**Comment by kenjewu** [comment]
@huangmingchuan  我也认为这里应该是不合法的，可以让
```c++
int *p = 0;
```
但是不能
```c++
int null = 0;
int *p = null;
```

**Comment by noyidoit** [comment]
书上P49原话:把int变量直接赋给指针是错误的操作,即使int变量的值恰好等于0也不行.

**Comment by noyidoit** [comment]
书上P49原话:
>把int变量直接赋给指针是错误的操作,即使int变量的值恰好等于0也不行.
