### ISSUE TITLE
练习4.25有疑惑

### ISSUE THREAD

**Issue by Snowball-Wang** [huangmingchuan/Cpp_Primer_Answers#19]
博主在练习4.25中的练习只是对"q"进行移位，但题目要求的是在移位之前还有个位取反的操作，答案有误。
我的答案是-7296。
思路是：`q`的二进制01110001取反得到的结果是10001110，其十进制为142，超出了8位char的表示范围（-128~127），char溢出时会循环表示，即128的表示是-128，所以142的表示是（-128+14 = -114），左移6位相当于乘以2^6，所以最后值为-7269。
欢迎大家讨论^.^

**Comment by nkkbr** [comment]
是不是应该是这样
01110001先提升为00000000_00000000_00000000_01110001 (32位int)
然后取反                11111111_11111111_11111111_10001110
然后左移                11111111_11111111_11100011_10000000   <-答案
