### ISSUE TITLE
练习9.4的程序有问题

### ISSUE THREAD

**Issue by blateyang** [huangmingchuan/Cpp_Primer_Answers#20]
练习9.4程序中该句```while (begin++ != end)```感觉有问题，会跳过第一个元素，自增运算应在下面的if语句执行之后再执行

**Comment by someonez56** [comment]
不光会跳过第一个元素,而且*begin最后会越界,报错

**Comment by SiberiaYaKing** [comment]
瞎说，begin++表达式返回begin被加之前的值，怎么跳过的第一个，没有运行过代码就没有发言权

**Comment by SiberiaYaKing** [comment]
另外，查不到值的情况下begin等于尾后迭代器，尾后迭代器是不能解引用的，这种情况下*begin当然会报错了

**Comment by someonez56** [comment]
@SiberiaYaKing 照你这么说,后加加永远不会加一了,自己去调试吧,实践才是真理

**Comment by SiberiaYaKing** [comment]
begin＋＋分两步，
返回begin被加之前的值
把begin加1
回去翻开c++primer1，131页

**Comment by SiberiaYaKing** [comment]
建议回去看看c++primer 131页
4.5递增和递减运算符

**Comment by someonez56** [comment]
你没理解,只是当前行不加加,后面会自动加一,你在网上找资料看吧(你看的C++primer大概是中文版).另外,纸上得来终觉浅,绝知此事要躬行.尽信书,不如无书.

**Comment by SiberiaYaKing** [comment]
@someonez56那请问你调试得到的结果是怎样的呢？

**Comment by someonez56** [comment]
@SiberiaYaKing 当然是跳过第一个元素,我回复你之前就试过,不然不会轻易回答

**Comment by SiberiaYaKing** [comment]
@someonez56Show me the code

**Comment by someonez56** [comment]
你不会也调试了吗?!你试试vector的元素例如0,1,2,3.如何不跳第一个元素肯定会找到零,并且返回,这样也不会越界,find(vector.begin(),vector.end(),0)如果跳过会报错的

**Comment by SiberiaYaKing** [comment]
呃，不好意思，真的是我弄错了，纠结了一晚，终于想通了，贻笑大方，真是对不起

**Comment by SiberiaYaKing** [comment]
之前的评论我就删了，免得误导其他入坑的萌新

**Comment by someonez56** [comment]
好的
