### ISSUE TITLE
练习12.12的答案是不是点问题

### ISSUE THREAD

**Issue by Stephan14** [huangmingchuan/Cpp_Primer_Answers#30]
（d）应该是不合法的吧

**Comment by cao0507** [comment]
> （d）应该是不合法的吧

这是合法的，只是这样使用会使p指向的内存释放掉，在之后再使用p时可能会引发错误。可以看一下413页process的第二个例子。

**Comment by Stephan14** [comment]
是啊，我也是这么理解的，至少要设置为nullptr吧

**Comment by huangmingchuan** [comment]
@Stephan14 
process的调用是合法的，之后确实要把 p 设置为 nullptr，最好是全部使用智能指针，不手动去 new
