### ISSUE TITLE
关于练习6.24的问题

### ISSUE THREAD

**Issue by xclwt** [huangmingchuan/Cpp_Primer_Answers#45]
指针应该是支持下标索引的，原代码执行应当没有问题。

**Comment by xixixixixiao** [comment]
函数
```cpp
void print(const int ia[10]);
```
的形参期望的是传递一个容量为 10 的 `int` 类型数组, 编译器将其会忽略掉 10 而把形参当作 `const int * ia` 类型. 所以传递一个容量低于 10 的数组也是可以正常运行, 但函数体的迭代代码却会出现越界的未定义的行为.

**Comment by xclwt** [comment]
感谢解答：）
