### ISSUE TITLE
练习9.4答案有误

### ISSUE THREAD

**Issue by Noicdi** [huangmingchuan/Cpp_Primer_Answers#77]
`	while (begin++ != end)
	{
		if (*begin == i) 
			return true;
    }	`
在这段循环中，begin迭代器被++，导致在接下来的查找操作中无法对vector的第一个元素进行判断。

**Comment by Noicdi** [comment]
会忽略vector中的第一个元素，对后续元素进行对比判断

**Comment by RekiDunois** [comment]
```
do { 
    if (*begin == i) 
        return true; 
} while (begin++ != end)
```
这样呢

**Comment by Noicdi** [comment]
> ```
> do { 
>     if (*begin == i) 
>         return true; 
> } while (begin++ != end)
> ```
> 
> 这样呢

我看没问题，我是这样解决的
`
    while (begin != end)
        if (*begin++ == i)
            return true;
`
